"""Add breed column

Revision ID: 125fe23e08ea
Revises: 
Create Date: 2022-12-29 18:47:58.154560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125fe23e08ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppies', schema=None) as batch_op:
        batch_op.drop_column('breed')

    # ### end Alembic commands ###
